FROM quay.io/toolbx-images/archlinux-toolbox:latest

LABEL com.github.containers.toolbox="true" \
      usage="This image is meant to be used with the toolbox or distrobox command" \
      summary="A cloud-native terminal experience" \
      maintainer="ignaciosaleman@gmail.com"

COPY extra-packages /

# Update the system
RUN pacman -Syu --noconfirm

# Install packages, ensuring the extra-packages file is correctly formatted and contains valid packages
RUN pacman -S --noconfirm $(grep -v '^#' /extra-packages)

RUN rm /extra-packages

# If this fails can run manually after (since only need to do once)
RUN ln -fs /usr/local/bin/distrobox-host-exec /usr/bin/podman &&\
    ln -fs /usr/local/bin/distrobox-host-exec /usr/bin/flatpak
